sonar.projectKey=holiday-calendar_holiday-calendar-ts
sonar.organization=holiday-calendar

sonar.sources=packages/core/src,packages/western/src,packages/apac/src
sonar.tests=packages/core/src,packages/western/src,packages/apac/src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/dist/**,**/node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
